# manifests/base/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secret
  namespace: default-ns
type: Opaque
data:
  # Dummy values - base64 encoded
  # DB_PASSWORD: "changeme" -> Y2hhbmdlbWU=
  DB_PASSWORD: Y2hhbmdlbWU=
