apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - prometheus-deployment.yaml
  - grafana-config.yaml
  - grafana-deployment.yaml
  - loki-config.yaml
  - loki-deployment.yaml
  - promtail-config.yaml
  - promtail-daemonset.yaml
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: observability-stack
